# Generated by Django 5.1.1 on 2024-09-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_Image_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='text',
        ),
        migrations.AlterField(
            model_name='documents',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
