# Generated by Django 5.1.1 on 2024-09-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_Image_App', '0002_remove_documents_text_alter_documents_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
