# Generated by Django 5.1.1 on 2024-09-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_Image_App', '0003_rename_documents_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
