# Generated by Django 5.1.1 on 2024-09-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_Image_App', '0005_document_processed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(upload_to='OCR_Image_App/static/img/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='OCR_Image_App/static/processed_images/'),
        ),
    ]
